//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkModel.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClassbookEntities : DbContext
    {
        public ClassbookEntities()
            : base("name=ClassbookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Mark> Marks { get; set; }
        public virtual DbSet<Parent> Parents { get; set; }
        public virtual DbSet<StudentContactInfo> StudentContactInfoes { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<TeacherContactInfo> TeacherContactInfoes { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
    }
}
