//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parent
    {
        public int ParentId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string PersonalNumber { get; set; }
        public int StudentId { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
